version: '3.9'

services:

  react_web:
    build:
      context: ./web/
      dockerfile: dockerfile
      args:
        NGINX_VERSION: stable-alpine
    container_name: react_web
    volumes:
      - ./web/docker/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx/:/var/log/nginx
      
    ports:
      - 3000:80
    depends_on:
      - java_app
    networks:
      - tg_network
    

  java_app:
    container_name: java_app
    image: danielxx/java_app:1.0.0
    build:
      context: ./app/
      dockerfile: dockerfile
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    volumes:
      - ./logs/app:/app/logs 
    depends_on:
      - java_db
    networks:
      - tg_network

      
  java_db:
    container_name: java_db
    image: postgres:12
    ports:
      - 5432:5432
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./logs:/var/log/postgresql 
      - ./db/postgres/:/var/lib/postgresql/data/postgres/postgresql.conf
    networks:
      - tg_network
    
volumes:
  pgdata: {}

networks: 
  tg_network:
    driver: bridge

