FROM node:18-alpine as build

WORKDIR  '/web'

ENV PATH /web/node_modules/.bin:$PATH

COPY package*.json ./
RUN npm ci --silent
COPY . ./

RUN npm run build

FROM nginx:stable-alpine

COPY --from=build /web/dist /usr/share/nginx/html
# COPY ./docker/default.conf /etc/nginx/conf.d/default.conf
# COPY ./docker/certificates/ /etc/nginx/ssl

EXPOSE 80
# EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]